#这里控制整个config文件是否启用
enable: true
#config的版本
version: 13
# todo功能
push: ""
account:
  #登入账号只需要修改cookie就行了
  cookie: "_MHYUUID=572f0481-c507-4739-8cde-89de8a90e961; DEVICEFP_SEED_ID=ccea3962f0690e49; DEVICEFP_SEED_TIME=1754464510746; DEVICEFP=38d80ea35eb8f; MIHOYO_LOGIN_PLATFORM_LIFECYCLE_ID=2a2a8850ad; cookie_token_v2=v2_FZ5OrvahNdYHJyeQWYMjkGccy3Viugd4f6HW7hTjFE0HYApOtbzHnMe1_Lm-vsUgu0F40T4ccY3rZHZeB3ZT7Ei9kvM2inWTQv_JtwjsJ-67ILmwtrLM11-20zzKoP64FF4R3hRODzb6okK5hQ==.CAE=; account_mid_v2=0xpva6nmfk_mhy; account_id_v2=168406990; ltoken_v2=v2_xUO9OUYwDjxsoYLWLkukDbYrEVQJbDUSWhfgGask1EknpYNJkMjzAZt5z9pKMYl1eYKBwBq-xpyYzI9Gfx527KjDt7ZOVyXhVo09eegcVomU8t4ZhD43rzh_jaJYiQPf2h8BuwlBTkQjvNmcwg==.CAE=; ltmid_v2=0xpva6nmfk_mhy; ltuid_v2=168406990; cookie_token=Lah86FBIQpqNNOWIc98xS5onHcgofYgpzlJb9N06; account_id=168406990; ltoken=NmZrFD6Gj2pQFkU5agK3HpsOBd3UEDMOxRHkhxyE; ltuid=168406990"
  stuid: ""
  stoken: "v2_x36kxvnjedfw5wcLe8v7bFgLBhMe_JNecnfz9GX3VfXFFBOWfrq35za84pjPWjbJ9ObFBHG2FRQMyByxrR34DVbG2CioCOkxEtyW4pw7iqhwFPRHzTZpm2UKr8bA40OvCVIEo_i35Q==.CAE="
  mid: ""
device:
  name: "Xiaomi MI 6"
  model: "Mi 6"
  # 此处脚本随机生成
  id: ""
mihoyobbs:
  #控制bbs功能是否启用
  enable: true
  #社区签到
  checkin: true
  #签到的社区列表 详情可以看config文件夹下面的readme
  checkin_list:
    - 5
    - 2
    - 6
    - 8
  #看帖
  read: true
  #点赞帖子
  like: true
  #取消点赞
  cancel_like: true
  #分享帖子
  share: true
# 游戏签到
games:
  #国服控制区域
  cn:
    #控制是否启用国内签到
    enable: true
    #配置签到用的ua 脚本会在后面自动加上miHoYoBBS/版本号 ,请复制的时候不要带miHoYoBBS/版本
    useragent: "Mozilla/5.0 (Linux; Android 12; Unspecified Device) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36"
    #重试次数
    retries: 3
    #原神
    genshin:
      #控制是否启用签到，下面一致
      checkin: true
      #这里是不签到的账号，填入文本型数据 示例["114514","1919810"](也许你这边是和checkin_list那块一样)，下面一致
      black_list: []
    #崩坏2
    honkai2:
      checkin: false
      black_list: []
    #崩坏3
    honkai3rd:
      checkin: false
      black_list: []
    #未定事件簿
    tears_of_themis:
      checkin: false
      black_list: []
    # 崩坏: 星穹铁道
    honkai_sr:
      checkin: true
      black_list: []
    #绝区零
    zzz:
      checkin: true
      black_list: []
  #国际服控制区域
  os:
    enable: false
    # 国际服专用Cookie填写
    cookie: ""
    # 国际服语言
    lang: "zh-cn"
    genshin:
      checkin: false
      black_list: []
    honkai3rd:
      checkin: false
      black_list: [ ]
    tears_of_themis:
      checkin: false
      black_list: []
    honkai_sr:
      checkin: false
      black_list: []
    zzz:
      checkin: false
      black_list: []
#云游戏专区
cloud_games:
  # 控制整个云游戏的签到
  cn:
    enable: true
    #云原神
    genshin:
      #开启签到
      enable: true
      #这里填入抓包获得的token，支持多个
      token: "ai=4;ci=1;oi=168406990;ct=v2_26438181f73c10003c154e51a840d9b193693e87;si=6c8b4855b49846d70603089d8aef9f8a8c1fd4fe9a81d369307dcaacd1bee22c;bi=hk4e_cn"
    #云绝区零
    zzz:
      enable: false
      token: ""
  os:
    lang: "zh-cn"
    enable: false
    genshin:
      enable: false
      token: ""
competition:
  enable: false
  genius_invokation:
    enable: false
    account: []
    checkin: false
    weekly: false
