#这里控制整个config文件是否启用
enable: false
#config的版本
version: 13
# todo功能
push: ""
account:
  #登入账号只需要修改cookie就行了
  cookie: "_MHYUUID=7b8aed30-8ca6-4cdd-b4ff-29611d662530; DEVICEFP_SEED_ID=e9b5df83e72e241d; DEVICEFP_SEED_TIME=1754464960366; DEVICEFP=38d80ea36c4eb; MIHOYO_LOGIN_PLATFORM_LIFECYCLE_ID=7883b3c033; ltoken_v2=v2_Yh6KfMhvb1rjg28Vv0uHLrt9B382b-mPTruyaOHi4E_Y4xN7H0T3OYLdFLmMIOOa_5U23s7H2gVjd-jSzyBCfYy_R-T4uhSw2HGeX7LIUWNjJWywooW6_UGyzudQ9zp5AzhxRQZrZxDwC-LDGB8=.CAE=; ltmid_v2=01wbuaanmw_mhy; ltuid_v2=438644541; cookie_token_v2=v2_7YLMoC7v_uAFg7WkMj2SmVliOMoyMpnUC4bTfo2kMg-wR2rSCyooUBnIfS18kWgNXfOSP20fPq67SGKWepQoHLdkGaGD_MkB2iafqLkPde9EoRYPVqBBhQdXZApUf95bwFWvNcdz3WqNwoEPbQ==.CAE=; account_mid_v2=01wbuaanmw_mhy; account_id_v2=438644541; cookie_token=PQrvYSF1RCSmIdJnBYgA4diiUT9oyXBM0wh4rftp; account_id=438644541; ltoken=S3wpcwi7Y5BHnGP7Xio7fUziInkT9CZrK8K4eWze;"
  stuid: ""
  stoken: "v2_BETxWO2VulkNJeaZYclBQKsNTHeRrOsOk-MwUS02Ls1CQroEnlTZTDgR6XKBBPhNJPFTqw_w9LuadANr88SpSVAYk8tSZpc0DSQN_bnJkmcarUvp36az0wAw6a_L8T5kW8b73jhmskw=.CAE="
  mid: ""
device:
  name: "Xiaomi MI 6"
  model: "Mi 6"
  # 此处脚本随机生成
  id: ""
mihoyobbs:
  #控制bbs功能是否启用
  enable: true
  #社区签到
  checkin: true
  #签到的社区列表 详情可以看config文件夹下面的readme
  checkin_list:
    - 6
    - 5
  #看帖
  read: true
  #点赞帖子
  like: true
  #取消点赞
  cancel_like: true
  #分享帖子
  share: true
# 游戏签到
games:
  #国服控制区域
  cn:
    #控制是否启用国内签到
    enable: true
    #配置签到用的ua 脚本会在后面自动加上miHoYoBBS/版本号 ,请复制的时候不要带miHoYoBBS/版本
    useragent: "Mozilla/5.0 (Linux; Android 12; Unspecified Device) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36"
    #重试次数
    retries: 3
    #原神
    genshin:
      #控制是否启用签到，下面一致
      checkin: false
      #这里是不签到的账号，填入文本型数据 示例["114514","1919810"](也许你这边是和checkin_list那块一样)，下面一致
      black_list: []
    #崩坏2
    honkai2:
      checkin: false
      black_list: []
    #崩坏3
    honkai3rd:
      checkin: false
      black_list: []
    #未定事件簿
    tears_of_themis:
      checkin: false
      black_list: []
    # 崩坏: 星穹铁道
    honkai_sr:
      checkin: true
      black_list: []
    #绝区零
    zzz:
      checkin: false
      black_list: []
  #国际服控制区域
  os:
    enable: false
    # 国际服专用Cookie填写
    cookie: ""
    # 国际服语言
    lang: "zh-cn"
    genshin:
      checkin: false
      black_list: []
    honkai3rd:
      checkin: false
      black_list: [ ]
    tears_of_themis:
      checkin: false
      black_list: []
    honkai_sr:
      checkin: false
      black_list: []
    zzz:
      checkin: false
      black_list: []
#云游戏专区
cloud_games:
  # 控制整个云游戏的签到
  cn:
    enable: true
    #云原神
    genshin:
      #开启签到
      enable: false
      #这里填入抓包获得的token，支持多个
      token: "ai=4;ci=1;oi=168406990;ct=v2_26438181f73c10003c154e51a840d9b193693e87;si=6c8b4855b49846d70603089d8aef9f8a8c1fd4fe9a81d369307dcaacd1bee22c;bi=hk4e_cn"
    #云绝区零
    zzz:
      enable: false
      token: ""
  os:
    lang: "zh-cn"
    enable: false
    genshin:
      enable: false
      token: ""
competition:
  enable: false
  genius_invokation:
    enable: false
    account: []
    checkin: false
    weekly: false
