#这里控制整个config文件是否启用
enable: true
#config的版本
version: 13
# todo功能
push: ""
account:
  #登入账号只需要修改cookie就行了
  cookie: "_MHYUUID=b61eaec3-5054-480b-aa99-fa7da92ee87e; DEVICEFP_SEED_ID=02cf800be1dc4a57; DEVICEFP_SEED_TIME=1737815686559; _ga=GA1.1.1904645100.1737815687; DEVICEFP=38d804182ddc3; MIHOYO_LOGIN_PLATFORM_LIFECYCLE_ID=9dcbf4d3ec; account_mid_v2=0xpva6nmfk_mhy; account_id_v2=168406990; ltmid_v2=0xpva6nmfk_mhy; ltuid_v2=168406990; cookie_token=zG7vjMsPL8CXuLrHN6tRPDwFzP1sAPrP0kKdSAaL; account_id=168406990; ltoken=oI2wHJxieTObgNvIiOIqBtZls8Jz5IOY0654S5Wl; ltuid=168406990; _ga_KS4J8TXSHQ=GS1.1.1737815686.1.1.1737815903.0.0.0; uni_web_token=1e569940663442efac120751143bf4b20xpva6nmfk_mhy; cookie_token_v2=v2_60gj0w03sl6b2UrSEfGkn4_HPTIpY44PRnbDaKHceYNE2-3q72OfaT2k5j8q4cbPjxPXmaUucsa0I6puJeznEEgQ-Q_bQwVhIxCjuEwEbL-6KuhCC40eTrqB2cpihM5eiaqb8_ZqyGVvXMerPxtp7g==.CAE=; ltoken_v2=v2_XYfcLF-VtXNMBcsMnT_tdarhGGQjmj9TopWD7NkzYCxAIkd_shs-ehtCXqTyIaZtnMWxj8UHKJWIYwrjUhlLGjoCzgAa7QvsWMKqypzaBtZ517vmxI2SEI6ozQ58jJvyRCc64MeOYJGwSMaYxEtF6Q==.CAE=; acw_tc=ac11000117378199999973568e493e33156118cf44d73a3f3501e7641c3c84"
  stuid: ""
  stoken: "v2_91r4utAEr3kXKLHhdRxMzVzw53p8tvmYZQJAqRYx-56PPxcJCiibm68ncMhKfPAMxN4CZBKStwsw8zuGwMKV9jBhzFvWCiCpiWFxnMDTbofGPRSyuTsWNuMNXbIuRvgluVGkfQuQ_g==.CAE="
  mid: ""
device:
  name: "Xiaomi MI 6"
  model: "Mi 6"
  # 此处脚本随机生成
  id: ""
mihoyobbs:
  #控制bbs功能是否启用
  enable: true
  #社区签到
  checkin: true
  #签到的社区列表 详情可以看config文件夹下面的readme
  checkin_list:
    - 5
    - 2
  #看帖
  read: true
  #点赞帖子
  like: true
  #取消点赞
  cancel_like: true
  #分享帖子
  share: true
# 游戏签到
games:
  #国服控制区域
  cn:
    #控制是否启用国内签到
    enable: true
    #配置签到用的ua 脚本会在后面自动加上miHoYoBBS/版本号 ,请复制的时候不要带miHoYoBBS/版本
    useragent: "Mozilla/5.0 (Linux; Android 12; Unspecified Device) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36"
    #重试次数
    retries: 3
    #原神
    genshin:
      #控制是否启用签到，下面一致
      checkin: true
      #这里是不签到的账号，填入文本型数据 示例["114514","1919810"](也许你这边是和checkin_list那块一样)，下面一致
      black_list: []
    #崩坏2
    honkai2:
      checkin: false
      black_list: []
    #崩坏3
    honkai3rd:
      checkin: false
      black_list: []
    #未定事件簿
    tears_of_themis:
      checkin: false
      black_list: []
    # 崩坏: 星穹铁道
    honkai_sr:
      checkin: true
      black_list: []
    #绝区零
    zzz:
      checkin: true
      black_list: []
  #国际服控制区域
  os:
    enable: false
    # 国际服专用Cookie填写
    cookie: ""
    # 国际服语言
    lang: "zh-cn"
    genshin:
      checkin: false
      black_list: []
    honkai3rd:
      checkin: false
      black_list: [ ]
    tears_of_themis:
      checkin: false
      black_list: []
    honkai_sr:
      checkin: false
      black_list: []
    zzz:
      checkin: false
      black_list: []
#云游戏专区
cloud_games:
  # 控制整个云游戏的签到
  cn:
    enable: true
    #云原神
    genshin:
      #开启签到
      enable: true
      #这里填入抓包获得的token，支持多个
      token: "ai=4;ci=1;oi=168406990;ct=v2_dc5dc96b6986522c5b6e4c3ddc8a667f085ee100;si=527368171a8dda1521a682921416f0391dbc420849de9cef367b6e945738bc32;bi=hk4e_cn"
    #云绝区零
    zzz:
      enable: false
      token: ""
  os:
    lang: "zh-cn"
    enable: false
    genshin:
      enable: false
      token: ""
competition:
  enable: false
  genius_invokation:
    enable: false
    account: []
    checkin: false
    weekly: false
