name: Deploy Project

on:
  push:
    branches:
      - main  # 监听 push 到 main 分支的事件
  pull_request:
    branches:
      - main  # 监听针对 main 的 PR
  schedule:
    - cron: '30 22 * * *'  # 每天 09:30 UTC 时间
  workflow_dispatch:  # 手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码库
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # 指定 Python 版本

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # 4. 启动主程序
      - name: Start the main thread
        run: |
          python main_multi.py autorun
